---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: freebsd-10.3
    driver:
      synced_folders: 
       - [".", "/vagrant", "disabled: true"]
      customize:
        cpus: 2
        memory: 5120

suites:
  - name: default-ftb
    run_list:
      - recipe[ftb_server::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      ftb_server:
        pack:
          name: "FTBInfinityLite110"
          version: "1.4.1"
  - name: with_map-ftb
    run_list:
      - recipe[ftb_server::mod_dynmap]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      ftb_server:
        pack:
          name: "FTBHorizonsIII"
          version: "1.0.0"
  - name: default-forge
    run_list:
      - recipe[ftb_server::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      ftb_server:
        pack:
          base_url: https://media.forgecdn.net/files/2700/952/PO3-3.0.40-SERVER.zip
          name: "ProjectOzone3"
          version: "3.0.40"
          is_forge_pack: true
  - name: with_map-forge
    run_list:
      - recipe[ftb_server::mod_dynmap]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      ftb_server:
        pack:
          base_url: https://media.forgecdn.net/files/2700/952/PO3-3.0.40-SERVER.zip
          name: "ProjectOzone3"
          version: "3.0.40"
          is_forge_pack: true
